In [1]:
%pip install pandas numpy

Collecting pandas
  Downloading pandas-3.0.0-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Using cached numpy-2.4.1-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mukun\onedrive\desktop\deep learning & agentic ai\project_section\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\mukun\onedrive\desktop\deep learning & agentic ai\project_section\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\mukun\onedrive\desktop\deep learning & agentic ai\project_section\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 985.5 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.7 MB 1.1 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.7 MB 1.1 MB/s eta 0:00:08
   ------ --------------------------------- 1.6/9.7 MB 1.3 MB/s eta 0:00:07
   ------- -------------------------------- 1.8/9.7 MB 1.4 MB/s eta 0:00:06
   --------- ------------------------------ 2.4/9.7 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.7 MB 1.6 MB/s eta 0:00:05
   -------------- ------------------------- 3.4/9.7 MB 1.7 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.7 MB 1.7 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.7 MB 1.8 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.7 MB 1.9 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.7 MB 1.9 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.7 MB 2.0 MB/s eta 0:00:02
   ---------------------------- ----------- 6.8/9.7 MB 2.0 MB/s eta 0:00:02
   ----------------------------- ---------- 7.1/9.7 MB 2.0 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.7 MB 2.0 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.7 MB 2.0 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.7 MB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.7 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 2.1 MB/s  0:00:05
Using cached numpy-2.4.1-cp312-cp312-win_amd64.whl (12.3 MB)
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed numpy-2.4.1 pandas-3.0.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("data/imdb_movies.csv")
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdb_id      4 non-null      str
 1   title        4 non-null      str
 2   year         4 non-null      int64
 3   genre        4 non-null      str
 4   director     4 non-null      str
 5   actors       4 non-null      str
 6   imdb_rating  4 non-null      float64
 7   imdb_votes   4 non-null      str
 8   box_office   4 non-null      str
 9   country      4 non-null      str
 10  language     4 non-null      str
dtypes: float64(1), int64(1), str(9)
memory usage: 484.0 bytes

In [4]:
data.isna().sum()

imdb_id        0
title          0
year           0
genre          0
director       0
actors         0
imdb_rating    0
imdb_votes     0
box_office     0
country        0
language       0
dtype: int64

In [5]:
data.head()

,imdb_id,title,year,genre,director,actors,imdb_rating,imdb_votes,box_office,country,language
0,tt3896198,Guardians of the Galaxy Vol. 2,2017,"Action, Adventure, Comedy",James Gunn,"Chris Pratt, Zoe Saldaña, Dave Bautista",7.6,"816,421","$389,813,101",United States,English
1,tt1375666,Inception,2010,"Action, Adventure, Sci-Fi",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",8.8,"2,767,518","$292,587,330","United States, United Kingdom","English, Japanese, French"
2,tt0111161,The Shawshank Redemption,1994,Drama,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton",9.3,"3,136,948","$28,767,189",United States,English
3,tt0468569,The Dark Knight,2008,"Action, Crime, Drama",Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart",9.1,"3,115,102","$534,987,076","United States, United Kingdom","English, Mandarin"

In [6]:
data.describe()

              year  imdb_rating
count     4.000000     4.000000
mean   2007.250000     8.700000
std       9.639329     0.761577
min    1994.000000     7.600000
25%    2004.500000     8.500000
50%    2009.000000     8.950000
75%    2011.750000     9.150000
max    2017.000000     9.300000

In [1]:
import pandas as pd
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",   # ← important
    port=3306,
    database="imdb",
    user="root",
    password=""
)

df = pd.read_sql("SELECT * FROM movies", conn)
conn.close()

df.head()

C:\Users\mukun\AppData\Local\Temp\ipykernel_15228\1674557168.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM movies", conn)

,imdb_id,title,year,genre,director,actors,imdb_rating,imdb_votes,box_office,country,language,created_at
0,tt0111161,The Shawshank Redemption,1994,Drama,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton",9.3,"3,136,948","$28,767,189",United States,English,2026-01-29 16:09:59
1,tt0468569,The Dark Knight,2008,"Action, Crime, Drama",Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart",9.1,"3,115,102","$534,987,076","United States, United Kingdom","English, Mandarin",2026-01-29 16:09:59
2,tt1375666,Inception,2010,"Action, Adventure, Sci-Fi",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",8.8,"2,767,518","$292,587,330","United States, United Kingdom","English, Japanese, French",2026-01-29 16:09:59
3,tt3896198,Guardians of the Galaxy Vol. 2,2017,"Action, Adventure, Comedy",James Gunn,"Chris Pratt, Zoe Saldaña, Dave Bautista",7.6,"816,421","$389,813,101",United States,English,2026-01-29 16:09:59

In [2]:
df.info()
df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdb_id      4 non-null      str
 1   title        4 non-null      str
 2   year         4 non-null      str
 3   genre        4 non-null      str
 4   director     4 non-null      str
 5   actors       4 non-null      str
 6   imdb_rating  4 non-null      float64
 7   imdb_votes   4 non-null      str
 8   box_office   4 non-null      str
 9   country      4 non-null      str
 10  language     4 non-null      str
 11  created_at   4 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(1), str(10)
memory usage: 516.0 bytes

imdb_id        0
title          0
year           0
genre          0
director       0
actors         0
imdb_rating    0
imdb_votes     0
box_office     0
country        0
language       0
created_at     0
dtype: int64

In [3]:
df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["imdb_votes"] = (
    df["imdb_votes"]
    .str.replace(",", "", regex=False)
    .astype(int)
)
df["box_office"] = (
    df["box_office"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["box_office"] = pd.to_numeric(df["box_office"], errors="coerce")

In [4]:
text_cols = ["genre", "director", "actors", "country", "language"]

def normalize_text(x):
    return x.lower().replace(",", " ").strip()

for col in text_cols:
    df[col] = df[col].apply(normalize_text)

In [5]:
df["content"] = (
    df["genre"] + " " +
    df["director"] + " " +
    df["actors"] + " " +
    df["language"] + " " +
    df["country"]
)

In [6]:
df.head()

,imdb_id,title,year,genre,director,actors,imdb_rating,imdb_votes,box_office,country,language,created_at,content
0,tt0111161,The Shawshank Redemption,1994,drama,frank darabont,tim robbins morgan freeman bob gunton,9.3,3136948,28767189,united states,english,2026-01-29 16:09:59,drama frank darabont tim robbins morgan freem...
1,tt0468569,The Dark Knight,2008,action crime drama,christopher nolan,christian bale heath ledger aaron eckhart,9.1,3115102,534987076,united states united kingdom,english mandarin,2026-01-29 16:09:59,action crime drama christopher nolan christi...
2,tt1375666,Inception,2010,action adventure sci-fi,christopher nolan,leonardo dicaprio joseph gordon-levitt ellio...,8.8,2767518,292587330,united states united kingdom,english japanese french,2026-01-29 16:09:59,action adventure sci-fi christopher nolan le...
3,tt3896198,Guardians of the Galaxy Vol. 2,2017,action adventure comedy,james gunn,chris pratt zoe saldaña dave bautista,7.6,816421,389813101,united states,english,2026-01-29 16:09:59,action adventure comedy james gunn chris pra...

In [7]:
df.describe()

,year,imdb_rating,imdb_votes,box_office,created_at
count,4.000000,4.000000,4.000000e+00,4.000000e+00,4
mean,2007.250000,8.700000,2.458997e+06,3.115387e+08,2026-01-29 16:09:59
min,1994.000000,7.600000,8.164210e+05,2.876719e+07,2026-01-29 16:09:59
25%,2004.500000,8.500000,2.279744e+06,2.266323e+08,2026-01-29 16:09:59
50%,2009.000000,8.950000,2.941310e+06,3.412002e+08,2026-01-29 16:09:59
75%,2011.750000,9.150000,3.120564e+06,4.261066e+08,2026-01-29 16:09:59
max,2017.000000,9.300000,3.136948e+06,5.349871e+08,2026-01-29 16:09:59
std,9.639329,0.761577,1.108051e+06,2.132096e+08,NaN

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdb_id      4 non-null      str
 1   title        4 non-null      str
 2   year         4 non-null      int64
 3   genre        4 non-null      str
 4   director     4 non-null      str
 5   actors       4 non-null      str
 6   imdb_rating  4 non-null      float64
 7   imdb_votes   4 non-null      int64
 8   box_office   4 non-null      int64
 9   country      4 non-null      str
 10  language     4 non-null      str
 11  created_at   4 non-null      datetime64[us]
 12  content      4 non-null      str
dtypes: datetime64[us](1), float64(1), int64(3), str(8)
memory usage: 548.0 bytes

In [9]:
df.isna().sum()

imdb_id        0
title          0
year           0
genre          0
director       0
actors         0
imdb_rating    0
imdb_votes     0
box_office     0
country        0
language       0
created_at     0
content        0
dtype: int64